[person programming language="python";coding="python";age=13;hobby="Coding";]
    [<name> code=false;]
        [<name1> mode="test";]
            [<name2> name="pyml";]
                [<name3> type="ml"]
                    Abdul Wahab
                [</name3>]
            [</name2>]
        [</name1>]
    [</name>]
[/person]